# Generated by Django 5.0.4 on 2024-06-15 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('expiry_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
